version: "3.9"

services:
  web:
    build: .
    container_name: ort_web
    env_file:
      - .env
    command: /entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: ort_nginx
    depends_on:
      - web
    ports:
      - "1111:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:


